
# Omniscient - Command History Tracker
# Generated by: omniscient init
# Add this to your ~/.bashrc (Linux) or ~/.bash_profile (macOS)

# NOTE: Requires bash-preexec library
# Install with:
# curl -sSL https://github.com/rcaloras/bash-preexec/raw/master/bash-preexec.sh -o ~/.bash-preexec.sh
# Then add to your bash profile: source ~/.bash-preexec.sh

# Start timer before command execution
_omniscient_preexec() {
    _OMNISCIENT_START=$(date +%s%N)
}

# Capture command after execution
_omniscient_precmd() {
    local exit_code=$?
    local cmd=$(history 1 | sed 's/^[ ]*[0-9]*[ ]*//')

    if [[ -n "$_OMNISCIENT_START" ]]; then
        local end=$(date +%s%N)
        local duration=$(( (end - _OMNISCIENT_START) / 1000000 ))

        # Run capture in background to avoid blocking shell
        # Redirect output and disown to prevent job notifications
        omniscient capture --exit-code "$exit_code" --duration "$duration" "$cmd" &>/dev/null &
        disown

        unset _OMNISCIENT_START
    fi
}

# Register hooks with bash-preexec
preexec_functions+=(_omniscient_preexec)
precmd_functions+=(_omniscient_precmd)

